export const DEMO_JOBS = [
  {
    id: 'demo-plomberie-bamako',
    title: 'Réparer une fuite dans une cuisine',
    description: 'Recherche d’un plombier fiable pour réparer une fuite et vérifier les raccords de la cuisine.',
    status: 'open',
    category: 'Plomberie',
    location_text: 'Bamako, Mali',
    budget_min: 25000,
    budget_max: 40000,
    estimated_duration: '1 journée',
  },
  {
    id: 'demo-peinture-dakar',
    title: 'Repeindre deux pièces d’un appartement',
    description: 'Un travail soigné est recherché pour préparer les murs et repeindre deux pièces avant emménagement.',
    status: 'open',
    category: 'Peinture',
    location_text: 'Dakar, Sénégal',
    budget_min: 60000,
    budget_max: 90000,
    estimated_duration: '2 à 3 jours',
  },
  {
    id: 'demo-electricite-ouaga',
    title: 'Installer des luminaires dans un commerce',
    description: 'Installation de six luminaires et vérification du câblage dans un petit commerce.',
    status: 'open',
    category: 'Électricité',
    location_text: 'Ouagadougou, Burkina Faso',
    budget_min: 35000,
    budget_max: 55000,
    estimated_duration: '1 à 2 jours',
  },
];
